dd.config({
    agentId: _config.agentId,
    corpId: _config.corpId,
    timeStamp: _config.timeStamp,
    nonceStr: _config.nonceStr,
    signature: _config.signature,
    jsApiList: [
        'runtime.info',
        'device.notification.prompt',
        'biz.chat.pickConversation',
        'device.notification.confirm',
        'device.notification.alert',
        'device.notification.prompt',
        'biz.chat.open',
        'biz.util.open',
        'biz.user.get',
        'biz.contact.choose',
        'biz.telephone.call',
        'biz.util.uploadImage',
        'biz.ding.post',
		'biz.map.view',
		'biz.telephone.call',
		'device.audio.startRecord',
		'device.audio.stopRecord',
		'device.audio.translateVoice',
		'device.audio.download',
		'device.audio.play',
		'device.geolocation.get',
		'device.geolocation.start',
		'device.geolocation.stop']
});